<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="plan.parent.edit"
    errors="0" failures="1" hostname="" id="" package="parent" skipped="0"
    tests="1" time="28.75" timestamp="Mon, 30 Jul 2018 07:14:52 GMT">
  
    <testcase name="get edit_plan in youqikang" classname="plan.parent.edit" time="28.75" assertions="15">

    

    

    

    

    

    

    

    

    

    

    

    

    

      <failure message="Testing if the URL equals &#34;https://admin.check.elinkport.com/Mange/DiagnoseMange&#34;.">    at Object.get edit_plan in youqikang (D:\vue_test\tests\plan\parent\edit.js:59:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
