<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="user.list"
    errors="0" failures="1" hostname="" id="" package="user" skipped="0"
    tests="1" time="16.34" timestamp="Fri, 27 Jul 2018 02:33:08 GMT">
  
    <testcase name="get clients in youqikang" classname="user.list" time="16.34" assertions="8">

    

    

    

    

    

    

      <failure message="Testing if the URL equals &#34;https://admin.check.elinkport.com/SetUp/CustomerContactMange&#34;.">    at Object.get clients in youqikang (D:\vue_test\tests\user\index.js:29:21)
    at process._tickCallback (internal/process/next_tick.js:61:11)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
